import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel, Lobster_Two } from "next/font/google";
import { MealProvider } from "@/context/meal-context";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/manual/meal/app-sidebar";
import Link from "next/link";
import "./globals.css";

const lobster_two = Lobster_Two({
  variable: "--font-lobster-two",
  subsets: ["latin"],
  weight: ["400", "700"]
})

const cinzel = Cinzel({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased `}
        
      >
        <MealProvider>
          <SidebarProvider>
            <SidebarTrigger/>
            <AppSidebar/>
            {children}
            </SidebarProvider>
        </MealProvider>
      </body>
    </html>
  );
}
