import type { Metadata } from "next";
import { Lobster_Two } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/manual/general/app-sidebar";
import "./globals.css";
import { Provider } from "@/context/my-providers";

const lobster_two = Lobster_Two({
  variable: "--font-lobster-two",
  subsets: ["latin"],
  weight: ["400", "700"]
})


export const metadata: Metadata = {
  title: "Fuel Fit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lobster_two.variable} antialiased `}
        
      >
        <Provider>
          <SidebarProvider>
            <SidebarTrigger className="fixed border-2 border-primary bg-background rounded-full flex flex-col pt-12 pb-8 sm:hidden w-15 top-0 z-50" size={'default'}/>
            <AppSidebar/>
            {children}
            </SidebarProvider>
        </Provider>
      </body>
    </html>
  );
}
